project:
  type: website

website:
  title: "Alfie Chadwick"
  navbar:
    left:
      - href: pages/index.qmd
        text: Home
      - href: pages/about.qmd
        text: About
      - href: pages/posts/postList.qmd

format:
  html:
    theme: themes/theme.scss
    toc: true
    highlight-style: themes/code_block.css

