project:
  type: website

website:
  title: "Alfie Chadwick"
  navbar:
    left:
      - href: content/index.qmd
        text: Home
      - href: content/about.qmd
        text: About

format:
  html:
    theme: theme.scss
    toc: true
    highlight-style: code_block.css

