project:
  type: website

website:
  title: "Alfie Chadwick"
  navbar:
    right:
      - href: pages/posts/postList.qmd
      - href: pages/tags/tagList.qmd
        text: Tags
      - href: pages/reviews/reviews.qmd
        text: Reviews

format:
  html:
    theme: themes/theme.scss
    toc: true
    highlight-style: themes/code_block.css

