baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 10
title = "Alfie Chadwick"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/" 

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Posts"
    url = "/post/"
[[menu.main]]
    name = "Tags"
    url = "/tags"

[params]
    description = "A website built through Hugo and blogdown."
    dateform = "Jan 2, 2006"
    dateformNum = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    homeSubtitle = "A portfolio of all my silly ideas"
    disableReadOtherPosts = false
    enableSharingButtons = true
    enableGlobalLanguageMenu = false


    highlightjsVersion = "11.9.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", 'python', 'matlab']
    highlightjsTheme = "macchiato"


    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.9"


    customCSS = []
    customJS  = []
    justifyContent = false

    [params.footer]
    trademark = 2023
    rss = true
    copyright = true
    author = true
    topText = []
    bottomText = []

    [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    logoMark = ">"
    logoText = "$ cd /home/"
    logoHomeLink = "/"
    logoCursorColor = "#bb9af7"
    logoCursorAnimate = "2s"

[[params.social]]
name = "email"
url  = "mailto:alfiechadwick@hotmail.com"

[[params.social]]
name = "github"
url = "https://github.com/Fonzzy1"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/alfie-chadwick-6a773a94/"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

PygmentsCodeFences = true
PygmentsStyle = "monokai"
rssLimit  = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

