baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 10
title = "Alfie Chadwick"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/" 

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Posts"
    url = "/post/"

[params]
    description = "A website built through Hugo and blogdown."
    dateform = "Jan 2, 2006"
    dateformShort = "Jan 2"
    dateformNum = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    homeSubtitle = "Stuff I think about in the shower"
    disableReadOtherPosts = false
    enableSharingButtons = true
    enableGlobalLanguageMenu = false
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    customCSS = []
    customJS  = []
    justifyContent = false

    [params.footer]
    trademark = 2023
    rss = true
    copyright = true
    author = true
    topText = []
    bottomText = []

    [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    logoMark = ">"
    logoText = "$ cd /home/"
    logoHomeLink = "/"
    logoCursorColor = "#A020F0"
    logoCursorAnimate = "2s"

[[params.social]]
name = "email"
url  = "mailto:alfiechadwick@hotmail.com"

[[params.social]]
name = "github"
url = "https://github.com/Fonzzy1"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/alfie-chadwick-6a773a94/"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

PygmentsCodeFences = true
PygmentsStyle = "monokai"
rssLimit  = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"
buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false
