---
title: "Taylor Series for approximating ODEs"
author: Fonzzy
date: 2021-04-26T00:00:00+00:00
output: html_document
---

If you ever start doing university level maths, physics, chemistry or even economics, you will most likely start running into differential equations. These are equations that describe functions in terms of their derivatives. Normally in these classes, at least at the start, all the problems are solvable by hand with some fairly rudimentary algebra and calculus. However, if you ever try and work with these problems in the real world, you will quickly realise that a lot of differential equations aren't solvable.

This is where numerical methods become useful as they provide one the ability to approximate the solution of the differential equation without explicitly soliving it.

## Euler's Method
One of the first numerical methods that most people get taught is Euler's method. There are many [better writers](https://tutorial.math.lamar.edu/classes/de/eulersmethod.aspx) who can explain this method much better than me, so I won't go into too much detail. Essentially, this method uses the definition of the differential equation to calculate steps of a given length h. For an ODE (differential equation of one variable) of order n, the method can be described as:

$$ \begin{bmatrix}
y(x+h)\\
y'(x+h)\\
y''(x+h)\\
...\\
y^{n-1}(x+h)\\
\end{bmatrix} = \begin{bmatrix}
y(x)\\
y'(x)\\
y''(x)\\
...\\
y^{n-1}(x)\\
\end{bmatrix} + \begin{bmatrix}
h & 0 & 0 &  ... & 0\\
0 & h & 0 &  ... & 0\\
0 & 0 & h &  ... & 0\\
... & ... & ... &  ... & ...\\
0 & 0 & 0 &  ... & h\\
\end{bmatrix} \cdot \begin{bmatrix}
y'(x)\\
y''(x)\\
y'''(x)\\
...\\
y^{n}(x)\\
\end{bmatrix}$$

This can also be written as:

$$ \begin{bmatrix}
y(x+h)\\
y'(x+h)\\
y''(x+h)\\
...\\
y^{n}(x+h)\\
\end{bmatrix} = \begin{bmatrix}
1 & h & 0 &  ... & 0\\
0 & 1 & h &  ... & 0\\
0 & 0 & 1 &  ... & 0\\
... & ... & ... &  ... & ...\\
0 & 0 & 0 &  ... & 1\\
\end{bmatrix} \cdot \begin{bmatrix}
y(x)\\
y'(x)\\
y''(x)\\
...\\
y^{n}(x)\\
\end{bmatrix}$$


### How to expand the Euler method?
The Euler Method approximates functions as straight lines at each point and then approximates the function again at the next point. However, if the function is not much like a straight line then this approximation will fail to produce accurate results. Therefore, the question becomes how could one take into account the curve of the function between steps.

## Taylor Series
A solution to the problem posed above is to use a taylor series of the function, which describes a function as a polynomial determined by its derivatives. Explicitly, it is defined as :

$$ y(x) =  \sum_{n = 0}^{\infty}  \frac{\mathbb y^{n}(a)}{n!}\cdot(x - a)^n $$

Where $a$ is the point where the approximation is built.


When looking at the point $a + h$ exclusively, this formula transforms to:

$$ y(a+h) = \sum_{n = 0}^{\infty}  \frac{\mathbb y^{n}(a)}{n!}\cdot(h)^n $$


A nice property of the taylor series is that it has a really simple derivative function:

$$ y'(a+h) = \sum_{n = 0}^{\infty}  \frac{\mathbb y^{n+1}(a)}{n!}\cdot(h)^n $$
$$ y^m(a+h) = \sum_{n = 0}^{\infty}  \frac{\mathbb y^{n+m}(a)}{n!}\cdot(h)^n $$

For a given h, this function describes a linear combination of the derivatives of a function, which can then be writen as a matrix multiplication

$$ \begin{bmatrix}
y(x+h)\\
y'(x+h)\\
y''(x+h)\\
...\\
y^{n}(x+h)\\
\end{bmatrix} = \begin{bmatrix}
1 & \frac{h}{1!} & \frac{h^2}{2!} &  ... & \frac{h^n}{n!}\\
0 & 1 & \frac{h}{1!} &  ... & \frac{h^{n-1}}{(n-1)!}\\
0 & 0 & 1 &  ... & \frac{h^{n-2}}{(n-2)!}\\
... & ... & ... &  ... & ...\\
0 & 0 & 0 &  ... & 1\\
\end{bmatrix} \cdot \begin{bmatrix}
y'(x)\\
y''(x)\\
y'''(x)\\
...\\
y^{n}(x)\\
\end{bmatrix}$$

One can see that this step matrix is similar to the matrix that defines the steps of the Euler method, however the Euler method doesn't take into account each of the higher derivatives, whereas this new step matrix does.

Now expanding the input vector to contain x and h information;

$$ \begin{bmatrix}
h\\
x+h\\
y(x+h)\\
y'(x+h)\\
y''(x+h)\\
...\\
y^{n}(x+h)\\
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 0 & 0 & 0 &  ... & 0\\
1 & 1 & 0 & 0 & 0 &  ... & 0\\
0 & 0 & 1 & \frac{h}{1!} & \frac{h^2}{2!} &  ... & \frac{h^n}{n!}\\
0 & 0 & 0 & 1 & \frac{h}{1!} &  ... & \frac{h^{n-1}}{(n-1)!}\\
0 & 0 & 0 & 0 & 1 &  ... & \frac{h^{n-2}}{(n-2)!}\\
... & ... & ... & ... & ... &  ... & ...\\
0 & 0 & 0 & 0 & 0 &  ... & 1\\
\end{bmatrix} \cdot \begin{bmatrix}
h\\
x\\
y(x)\\
y'(x)\\
y''(x)\\
...\\
y^{n}(x)\\
\end{bmatrix}$$

## How to make the approximation fit the ODE
This pert of the problem has to be turned into two separate problems, one for ODEs that are exclusively linear combinations of the input vector and one they are not.
