---
title: 'A Follow Up on my Hottest 100 Predictions'
author: 'Alfie Chadwick'
date: '2024-02-03'
lastmod: "`r Sys.Date()`"
tags: ['Music']
output:
  blogdown::html_page
---


```{R setup,  include=FALSE}

library(tidyverse)
library(jsonlite)
library(patchwork)
library(lubridate)
library(xgboost)
library(catppuccin)

knitr::opts_chunk$set( echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE)


theme_dark_catppuccino <- function(base_size = 11, base_family = "") {
  theme_minimal(base_size = base_size, base_family = base_family) +
    theme(
      # Define colors
      text = element_text(color = "#cad3f5"),
      strip.text = element_text(colour = '#cad3f5'),
      
      # Background colors
      plot.background = element_rect(fill = "#24273a", color = NA),
      panel.background = element_rect(fill = "#1e2030", color = NA),
      plot.margin = margin(2, 2, 2, 2, "pt"),

      # Grid colors
      panel.grid.major = element_line(color = "#494d64", size = 0.25),
      panel.grid.minor = element_line(color = "#494d64", size = 0.25),
      
      # Axis colors and ticks
      axis.ticks = element_line(color = "#cad3f5"),
      axis.text = element_text(color = "#cad3f5"),
      axis.title = element_text(color = "#cad3f5"),
      axis.line = element_line(color = "#cad3f5"),
      
      # Legend colors
      legend.background = element_rect(fill = "#363a4f"),
      legend.text = element_text(color = "#cad3f5"),
      legend.title = element_text(color = "#cad3f5", face = "bold"),
      legend.position = "none",

      # Title and subtitle
      plot.title = element_text(color = "#b7bdf8", size = base_size * 1.2, 
                                hjust = 0.5, face = "bold"),
      plot.subtitle = element_text(color = "#b7bdf8", size = base_size * 0.9,
                                   hjust = 0.5),
                                   
      # Caption
      plot.caption = element_text(color = "#f4dbd6", hjust = 0.5, 
                                  size = base_size * 0.8)
    )
}

theme_set(theme_dark_catppuccino())

```

```{R dataset}

data_cols <- c(
  "weeks_with_more_than_7",
  "peak_week_JJJ",
  "peak_plays_JJJ",
  "first_play",
  "total_plays",
  "weeks_in_charts",
  "peak_in_charts",
  "chart_score"
)

clean_artist_name <- function(artist_string) {
  # Convert the string to lowercase
  artist_string <- tolower(artist_string)
  
  # remove any text within parentheses or 
  artist_string <- gsub("\\(.+?\\)", "", artist_string)
  # Remove content in square brackets
  artist_string <- gsub("\\[.+?\\]", "", artist_string)
  
main_artist <- unlist(strsplit(artist_string, " feat | featuring | ft | with | x | and | & | vs |, "))[1]

    main_artist <- iconv(main_artist, from = "UTF-8", to = "ASCII//TRANSLIT")
    main_artist <- gsub("[[:punct:]]", "", main_artist)
  
  # trim leading and trailing whitespace
  main_artist <- trimws(main_artist)
  
  return(main_artist)
}

clean_song_name <- function(song_string) {
  # Convert the string to lowercase
  song_string <- tolower(song_string)
  
  # remove any text within parentheses or 
  song_string <- gsub("\\(.+?\\)", "", song_string)
  # Remove content in square brackets
  song_string <- gsub("\\[.+?\\]", "", song_string)
  
  songname <- unlist(strsplit(song_string, " feat | featuring | ft | with "))[1]
  
  # trim leading and trailing whitespace
  songname <- trimws(songname)
  
  return(songname)
}


results <- read.csv('data/2023_results.csv')
xgb_model <- xgb.load('data/xgb_model.bin')
inferance <- readRDS("data/inferance.rds")
inferance[data_cols] <- lapply(inferance[data_cols], as.numeric)
inf <- as.matrix(inferance[, data_cols])
predictions <- predict(xgb_model, inf)
inferance$predicted_rank <- predictions

results <- results %>%
  mutate(
    Song = map_chr(Song, clean_song_name),
    Artist = map_chr(Artist, clean_artist_name)
  )

my_100 <- inferance  %>% 
  mutate(predicted_rank = rank(predicted_rank, ties.method = "first")) %>%
  filter(predicted_rank < 101)
```

In my [last post](/2024/01/26/predicting-the-2023-hottest-100/) I ended by planting my flag and making my predictions for the Hottest 100 for 2023. And on first glance, I'm pretty happy with myself, picking not only the top song, but a good chunk of the top 20. So today I just want to do a quick follow up on how I did.

# Top 20

```{R top-20}

results %>% 
  left_join(my_100) %>%
  select(Song, Artist, rank, predicted_rank) %>%
  arrange(rank) %>%  # Sort by rank
  select(Song, Artist,Predicted =  predicted_rank) %>%
  slice_head(n = 20) %>%       # Take the first 20 rows after sorting
  print(na.print = 'Not Ranked')         # Replace NA values with an empty string for printing
```

The top 10 seems okay, but i did miss a lot of the top 20 completely. I seemed to be undervaluing Australian artists such as Dom Dolla, Spacey Jane, and G Flip, as well as EDM as a genre, which made up a much greater portion of the top 20 than I predicted.


# Snubbed Songs

```{R snubs}

my_100 %>%
  left_join(results) %>%
  filter(is.na(rank)) %>%
  select(Song, Artist, rank, predicted_rank) %>%
  arrange(predicted_rank) %>%  # Sort by rank
  select(Song, Artist,Predicted =  predicted_rank) %>%
  print(na.print = '')         # Replace NA values with an empty string for printing
```

So there were 55 songs in my predictions that didn't make it into the countdown, including 3 of my top 20. Funily enough though, a lot of my predictions seemed to line up with peoples opions online with [Love Type](https://www.reddit.com/r/triplej/comments/1adh146/comment/kk1b24c/?utm_source=share&utm_medium=web2x&context=3), [Super Ego](https://www.reddit.com/r/triplej/comments/1adh146/comment/kk16o08/?utm_source=share&utm_medium=web2x&context=3) and [Adored](https://www.reddit.com/r/triplej/comments/1adh146/comment/kk1hqcl/?utm_source=share&utm_medium=web2x&context=3) all being mentioned as snubs from the hottest 100.


# Surprise Songs

```{R suroprise}

if (nchar(song) > 20) {
  song <- paste0(substr(song, 1, 17), "...")
}

my_100 %>%
  right_join(results) %>%
  filter(is.na(predicted_rank)) %>%
  select(Song, Artist, rank) %>%
  arrange(rank) %>%  # Sort by rank
  select(Song, Artist, rank) %>%
  print(na.print = '')
```

With 55 snubs, we are going to have 55 surprise songs. There doesn't seem to be  a massive trend here. G flip only made it into my countdown twice, so 5 of their songs are in this list. Its also interesting seeing which conventionally popular songs are part of this list.  Boy's a liar pt. 2  by Pinkpantheress and All American-Bitch which peaked at 2 and 10 on the aria charts were left out in my predictions, even though it predicted similar chart toppers in the top 10.

```{R suroprise-comps}

# Filter the songs of interest
filtered_songs <- inferance %>%
  filter(Song %in% c("all-american bitch", "boy's a liar pt. 2", "paint the town red", "vampire")) %>%
  select(- first_play)


# Melt the data for easy plotting using 'pivot_longer' from tidyr package
long_data <- filtered_songs %>%
  pivot_longer(cols = data_cols[!data_cols %in% 'first_play'], names_to = "Metrics", values_to = "Values")

ggplot(long_data, aes(x = Song, y = Values, fill = Song)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.7)) +
  facet_wrap(~ Metrics, scales = "free_y") + # Faceting by metrics, with separate y scales
  labs(x = "Song", y = "Value", title = "Comparison of Songs Across Inferance Features") +
  scale_fill_catppuccin(palette="macchiato",  reverse = FALSE) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Looking at these plots, it seems that the chart data for these songs didn't correctly join with the play data from triple J. After cleaning the names, I was hoping that there wouldn't be too much of a discrepancy. However, in the ARIA charts, "all-american bitch" is listed as "all-american b\*\*ch," and "boys a liar pt. 2" is listed as "boys a liar". This kind of discrepancy is probably present throughout my dataset and may have led to some major inaccuracies. However, it is also just part of life when dealing with text data.

# Did I do better than Warm Tuna?

Part of my mission when setting out to make these predictions was to do better than 100 Warm Tunas
